# Generated by Django 3.2.3 on 2021-11-08 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Account ID')),
                ('account_name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('ofx_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Name')),
            ],
            options={
                'ordering': ['account_id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Payment type')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('fit_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='FIT ID')),
                ('date_posted', models.DateField(verbose_name='Posting Date')),
                ('date_entered', models.DateField(verbose_name='Entry Date')),
                ('date_inserted', models.DateField(verbose_name='Date Inserted')),
                ('counter_party', models.CharField(max_length=255, verbose_name='Counter Party')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('transaction_type', models.CharField(max_length=255, verbose_name='Transaction type')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.account')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.paymenttype')),
            ],
            options={
                'ordering': ['date_posted', 'fit_id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionGroup',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Transaction group')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('detail_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Transaction Detail ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('comment', models.CharField(blank=True, max_length=4095, null=True, verbose_name='Comment')),
                ('fit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.transaction')),
                ('transaction_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.transactiongroup')),
            ],
            options={
                'ordering': ['fit_id'],
            },
        ),
    ]
