# Generated by Django 3.2.3 on 2021-11-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AlterField(
            model_name='account',
            name='ofx_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OFX Name'),
        ),
    ]
